### ISSUE TITLE
Missing types for `prism-code-editor/setups` import

### ISSUE THREAD

**Issue by dan-lee** [FIameCaster/prism-code-editor#1]
Hey @FIameCaster,

Excellent library, precisely what I needed!
I am getting some type errors when importing from the editor setups:

![CleanShot 2023-08-09 at 11 21 26@2x](https://github.com/FIameCaster/prism-code-editor/assets/571589/220f42b4-a3b5-481a-a812-9d4c8aee65e7)

>TS7016: Could not find a declaration file for module 'prism-code-editor/setups'. '.../prism-code-editor@0.0.3/node_modules/prism-code-editor/dist/setups.js' implicitly has an 'any' type.
>
>If the 'prism-code-editor' package actually exposes this module, try adding a new declaration (.d.ts) file containing `declare module 'prism-code-editor/setups';`

**Comment by FIameCaster** [comment]
Hey, glad you liked my library!

The issue seems to be that setups is imported from `dist/setups.js` while the declaration is located at `dist/setups/index.d.ts`. Moving the setups to `dist/setups/index.js` should solve the problem.

**Comment by dan-lee** [comment]
Thanks a lot! Keep up the good work :)
