### ISSUE TITLE
wordWrap conflicts with indentation guides

### ISSUE THREAD

**Issue by thdoan** [FIameCaster/prism-code-editor#16]
Steps to reproduce:

1. Go to https://prism-code-editor.netlify.app/
2. Update Config tab:
    `language: 'javascript',`
    `wordWrap: true,`
3. Click Run
4. Paste this code:

```
function test() {
  const re = /^test$/i;
  const obj = {
    "str": "string",
    "int": 1,
    "bool": true
  };
}
```

Notice that the indentation guides are no longer visible.

**Comment by FIameCaster** [comment]
This is intended behavior. The indent guides don't take line wrapping into consideration at all. Therefore they're made hidden with `display: none` if word-wrap is enabled. The extension not supporting word wrap is specified in the documentation.

Reworking the extension to support word wrap would be possible, but it would both lead to a larger bundle size and much worse performance. These tradeoffs are not worth it IMO.

I could make a separate indent guides extension that does support word wrap, but this is low priority.

**Comment by thdoan** [comment]
Ah, thanks for explaining the reasons. It's a fair trade-off ^^
