### ISSUE TITLE
Smooth following cursor

### ISSUE THREAD

**Issue by ThinLiquid** [FIameCaster/prism-code-editor#19]
This isn't a very urgent request but more of a QOL addition, but a smooth cursor that glides similar to VSCode or MS Word (the newer versions). I personally think that these look very nice and would be an amazing addition to the code editor!

**Comment by FIameCaster** [comment]
By "Smooth cursor" do you mean something similar to the cursor with `Cursor Blinking` set to `smooth` in VSCode settings?

**Comment by ThinLiquid** [comment]
No, I mean like when you type the caret glides, its this setting!
![image](https://github.com/FIameCaster/prism-code-editor/assets/56958664/195a59e0-f75e-4ebf-b08d-dfc2709cee69)

**Comment by FIameCaster** [comment]
This was easy to implement actually. I might consider making it an extension. [StackBlitz example](https://stackblitz.com/edit/vitejs-vite-sza5zx?file=src%2Fstyle.css,src%2Fextensions.ts&terminal=dev).

There is a small issue when word wrap is enabled though. I will improve it in version 3.3.2, but it's near impossible to fix properly.

**Comment by ThinLiquid** [comment]
Nice! Glad to see it working :3

**Comment by FIameCaster** [comment]
After further consideration, I won't be making an extension out of this. Implementing it yourself requires little code and an extension would be harder to customize.
