### ISSUE TITLE
Prismjs v2?

### ISSUE THREAD

**Issue by backspaces** [FIameCaster/prism-code-editor#2]
The prismjs site is pretty old, waiting on the v2 transition for more than a year.

What impact will this have on prism-code-editor?

**Comment by FIameCaster** [comment]
Currently prism-code-editor is using a patched Prism core with some v2 features added, and many of the grammars have been altered. Switching to Prism v2 would be a lot of work and will likely more than double the size of the core without adding anything useful for a code editor. Therefore, I'll instead keep maintaining my patched prism core and grammars. Doing a git diff between versions and implementing relevant changes to prism-code-editor for every Prism release should not be much work.

The Prism v2 branch has been stagnant for 6 months now, so I doubt it's coming any time soon. Once it does release, I'll think more about how to handle this. Something I might do is dropping the patch file and just putting the grammars and the Prism core in this repository directly, which will make it easier to implement more of the v2 features.

Hope this answers your questions.

**Comment by backspaces** [comment]
Thanks, very clear!
