### ISSUE TITLE
readonly code folder adding new lines?

### ISSUE THREAD

**Issue by ysk3a** [FIameCaster/prism-code-editor#25]
I'm not sure if this is just in the demo but i've also noticed an odd behavior in the examples under the example section.

The provided examples were mostly non readonly examples, that is, the examples did not use readonlyeditor() or use the readOnlyCodeFolding option.
So I tried to add them to see how it would look like and for some odd reason adding readOnlyCodeFolding add extra new lines at various locations.

forking one of the stackblitz examples, i've added the folding option and theres new lines added?
https://stackblitz.com/edit/vitejs-vite-ympxkc?file=src%2Fmain.ts

original:
![image](https://github.com/user-attachments/assets/ca731e9f-5de8-4d87-b5d5-2e0911682f62)

after adding readOnlyCodeFolding:
![image](https://github.com/user-attachments/assets/261e4740-bfbc-4101-8cda-07643058f20a)

**Comment by FIameCaster** [comment]
The `readOnlyCodeFolding` extension requires styles from `prism-code-editor/code-folding.css`. I'll usually document it if an extension requires extra styling, but I forgot to do so here. I will fix that.

**Comment by ysk3a** [comment]
I see.
It appears adding `import 'prism-code-editor/code-folding.css';` in addition to 'readOnlyCodeFolding` seems to have fixed the new line behavior as you have mentioned.
Thanks for the quick response! 👍
