### ISSUE TITLE
Add language via prism definition

### ISSUE THREAD

**Issue by qiushiyan** [FIameCaster/prism-code-editor#4]
Hi, thanks for creating the library. 

I want to register a custom language. What I have is a prism language definition as in https://prismjs.com/extending.html, I am not sure how to convert it to the `languageMap` object mentioned in the docs. 

It seems vite is automatically generating the grammar definition from prism definition in the build process. I think it's better to had a option to add a language that simply accepts the prism definition format at run time.

**Comment by FIameCaster** [comment]
The `languageMap` has nothing to do with Prism. It's for defining the bahavior of automatic indentation and comment toggling for a language. https://github.com/FIameCaster/prism-code-editor?tab=readme-ov-file#language-specific-behavior

If you want to add your own grammar definitions, just import the Prism core. Maybe I should make it clear in the readme that you can do this.

```javascript
import { Prism } from "prism-code-editor"

Prism.languages.whatever = {
  ...
}
```

Just be sure to add your grammar before creating any editors.
