### ISSUE TITLE
Can't find types

### ISSUE THREAD

**Issue by Mike-Bell** [FIameCaster/prism-code-editor#9]
My project setup is unable to find the included type definitions. Not sure why.

![image](https://github.com/FIameCaster/prism-code-editor/assets/8780033/db73993a-4b34-441c-8f69-5546b9dfd296)

Looking at your package.json, it looks like you're doing some "newer/fancier" things with your package setup that I'm unfamiliar with, so I'm not sure where the problem is, but I think I'm using a fairly straight-forward setup, so I'm surprised I have issues. I'm using TypeScript 5.2.2, vscode, and esbuild to build/bundle (though I don't think esbuild should be related here). If I have time, I'll try to do a "minimal repro" of how I got into this state - I have a bit going on in my project and I probably can't share it directly.

**Comment by FIameCaster** [comment]
What's the `moduleResolution` set to in `tsconfig.json`? Setting it to `Bundler`, `Node16` or `NodeNext` should work.

**Comment by Mike-Bell** [comment]
yep, `"moduleResolution": "Bundler"` seems to work for me... thanks!
